apiVersion: apps/v1
kind: Deployment
metadata:
  name: springcloud-eureka
  namespace: springcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      springcloud: eureka
  template:
    metadata:
      labels:
        springcloud: eureka
    spec:
      containers:
      - name: app
        image: cloudcamp/springcloud-eureka:latest
        #        resources:
        #          requests:
        #            memory: "700Mi"
        #          limits:
        #            memory: "1000Mi"
        ports:
        - containerPort: 8761
        env:
        - name: spring.profiles.active
          valueFrom:
            configMapKeyRef:
              name: springcloud
              key: spring.profile
        - name: spring.cloud.config.uri
          valueFrom:
            configMapKeyRef:
              name: springcloud
              key: springcloud.config.uri
        - name: eureka.datacenter
          valueFrom:
            configMapKeyRef:
              name: springcloud
              key: springcloud.eureka.datacenter
        - name: eureka.environment
          valueFrom:
            configMapKeyRef:
              name: springcloud
              key: springcloud.eureka.environment
        - name: eureka.client.serviceUrl.defaultZone
          valueFrom:
            configMapKeyRef:
              name: springcloud
              key: springcloud.eureka.uri
---
apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: springcloud
spec:
  selector:
    springcloud: eureka
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: eureka
  namespace: springcloud
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rule-type: "PathPrefixStrip"
    external-dns.alpha.kubernetes.io/target: home.cluster.camp
spec:
  rules:
    - host: eureka.cluster.camp
      http:
        paths:
          - path: /
            backend:
              serviceName: eureka
              servicePort: 8761

