server:
  port: 8761
spring:
  application:
    name: EUREKA
---
spring:
  profiles: dev
  boot:
    admin:
      context-path: /admin
      ui:
        public-url: https://eureka.cluster.camp/admin
  rabbitmq:
    host: rabbitmq.springcloud.svc.cluster.local
    port: 5672
    username: springcloud
    password: springcloud
eureka:
  instance:
    hostname: localhost
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: ALWAYS
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'