server:
  port: 8761
  use-forward-headers: true
spring:
  application:
    name: EUREKA
---
spring:
  profiles: dev
  boot:
    admin:
      contextPath: /sba
      ui:
        publicUrl: http://eureka.cluster.camp/sba
  rabbitmq:
    host: rabbitmq.springcloud.svc.cluster.local
    port: 5672
    username: springcloud
    password: springcloud
eureka:
  server:
    waitTimeInMsWhenSyncEmpty: 0
  client:
    registerWithEureka: false
    fetchRegistry: false
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: ALWAYS
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'