server:
  port: 8761
spring:
  application:
    name: EUREKA
---
spring:
  profiles: dev
  rabbitmq:
    host: rabbitmq.springcloud.svc.cluster.local
    port: 5672
    username: springcloud
    password: springcloud
eureka:
  instance:
    hostname: localhost
    leaseExpirationDurationInSeconds: 5
    leaseRenewalIntervalInSeconds: 3
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'