spring:
  application:
    name: EUREKA
  rabbitmq:
    host: rabbitmq.springcloud.svc.cluster.local
    port: 5672
    username: springcloud
    password: springcloud
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    leaseExpirationDurationInSeconds: 5
    leaseRenewalIntervalInSeconds: 3
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
