server:
  port: 8080
spring:
  application:
    name: hystrix
---
spring:
  profiles: ide
management:
  metrics:
    web:
      server:
        auto-time-requests: true
        requests-metric-name: http.server.requests
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
