apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: eureka
spec:
  rules:
  - host: eureka.k8s.com
    http:
      paths:
      - path: /
        backend:
          serviceName: eureka
          servicePort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: eureka
spec:
  selector:
    app: spring-cloud-eureka
  ports:
  - protocol: TCP
    port: 8761
    targetPort: 8761
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cloud-eureka
  template:
    metadata:
      labels:
        app: spring-cloud-eureka
    spec:
      containers:
      - name: app
        image: hubtea/spring-cloud-eureka:latest
        resources:
          requests:
            memory: "700Mi"
          limits:
            memory: "1000Mi"
        ports:
        - containerPort: 8761
        env:
        - name: spring.profiles.active
          valueFrom:
            configMapKeyRef:
              name: base-config
              key: spring.profiles.active
        - name: eureka.datacenter
          valueFrom:
            configMapKeyRef:
              name: base-config
              key: spring.cloud.eureka.datacenter
        - name: eureka.environment
          valueFrom:
            configMapKeyRef:
              name: base-config
              key: spring.cloud.eureka.environment
        - name: eureka.client.serviceUrl.defaultZone
          valueFrom:
            configMapKeyRef:
              name: base-config
              key: spring.cloud.eureka.uri
        - name: spring.cloud.config.uri
          valueFrom:
            configMapKeyRef:
              name: base-config
              key: spring.cloud.config.uri