language: java
jdk:
  - openjdk11
branches:
  only:
    - master
    - develop
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.gradle"
env:
  global:
    - secure: u37gl+5dOP65wm52rww+yanRJIyhJ4fBTd2l7KzHVC3jEaq5dfuiY6vi+/nMy/tLOO3zwMT1LQks19EHKhf1b3vds+Cpsl2AV+lEGM+VeGIjQL+XMvYGqCGoWAgdWNZ7gbFyZEub/ccdH0fJy7kygGxhxPN/X6I8BzlblvFcZ9bOKY+jAZ8SgmthYlPqbe4Buwm3WIRiEVkB8r11i9cNhVqHpW/3DAbLmfrVF+4n4G9rE30w4bz/gZwNhMtVSHtth0e0Zz0MwSB+T0kaVx+Nlhg83H0S1EiGOOFpbrzTErbJCPcBB4QbvtUvcnsNbpwgBd6EmVZh5k+/p3hzfNnIzoa/AwNqG6hSOelDtk9pVbrYsuJhuCTwaek1P281hZvTKSGi5rHnNxVUNrFesC7z/XkWlDU5cpS/MEPPjY+C79nUkDPqDl6R9Krop58C3UYbAa6CxM5RHDO6rP2X8VH+e7rVsLQ/O6TjEmxLxsN4rt5Yg5RagPhD9W5F9VTYalJif/y3OiaSgDGiVzOl8I9lJb7T9pKIjMhyk9t5+phMLEz9DpLGmOh8bPDc4a62Kd0mN12X90XTAtQKf1V9S/nbOF+YFhCKANfrBuZDomRw3AMdPPDfQUJIWCDTiX2GbdgWt6RTg37emiiqEOm5LTyrxOM5YARskY9D6a+ZcyE1t5k=
    - secure: CntQX0592ZEoJDOz5ZhMFZF60+6SDFAULz/enwjAjWX9fDj/A+2dhOiVy8avLprzJd34aKjD5Lr3NuRTkU1httKycU5HvM0Rtlt6G6p4jxkDOGu1yiCH7Xmf/xCRIcS8NVNajk/RWwJztps/vCToKy3qztD5bRo+cVCx2lhb11Axm5dgzoLoKnESbVvauSd701HUA+FL2Z+iJztBVE4TtMXpyU9H4sAI2jYDAy+oNKntMy+929M0MVlAI4TjD1q0N7TeMA5lUV+qx0rNyVArGNZr1IitWkv+6+JzAB2GGkMe6IuNpKd8Sk3H2keZQYYMGU8q5+LeCVVheeDOQl29Cf09LVy4bIyD8GdOCpdOBd/G2r/24boRZwBUHyBigAhPm86hnyFF3R8DSX3aa/NfzABIJaPO9kIYm9o4+zTVxzMR9sQQm+wYYA+CGR5oiiKUzMxPUDe9Iiy2t6uGxjfBBxIsoETDaGSRpyHwH76q2El3FYVpypl4fkIuShDjSy8p4/KXkijOLL1Dwv2HC4e7XrH192WSGamrWU58FJHWnOjoEw57fMUoSBMsIx01lzyfz9h+vVew9VqZqdPT3iEFQZFXAt92z8qVEPu2/1hNZdrezclkWJs0anZNf1++BM5TXsWkdbu7w86gEIW8jQJ/p2iKFQEJsN3cMuzoCenr7zw=
script:
  - "./gradlew check"
  - "./gradlew jib -Djib.to.auth.username=$DOCKER_USER -Djib.to.auth.password=$DOCKER_PASS"
