server:
  port: 8888
  ssl:
    enabled: false
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/clustercamp/spring-cloud-java11.git
          searchPaths: /configurations
