server:
  port: 8080
spring:
  application:
    name: zuul
---
spring:
  profiles: ide
  zipkin:
    baseUrl: http://zipkin.development.svc.cluster.local:9411
  sleuth:
    sampler:
      percentage: 0.2
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://eureka.cluster.camp/eureka/
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
zuul:
  routes:
    user:
      path: /user/**
      stripPrefix: false
      sensitiveHeaders:
      serviceId: API-USER
    api-user:
      path: /api-user/**
      serviceId: API-USER
    good:
      path: /good/**
      stripPrefix: false
      sensitiveHeaders:
      serviceId: API-GOOD
    api-good:
      path: /api-good/**
      serviceId: API-GOOD
    sale:
      path: /sale/**
      stripPrefix: false
      sensitiveHeaders:
      serviceId: API-SALE
    api-sale:
      path: /api-sale/**
      serviceId: API-SALE
    ship:
      path: /ship/**
      stripPrefix: false
      sensitiveHeaders:
      serviceId: API-SHIP
    api-ship:
      path: /api-ship/**
      serviceId: API-SHIP
    oauth:
      path: /oauth/**
      stripPrefix: false
      sensitiveHeaders:
      serviceId: SECURITY
  add-proxy-headers: true
security:
  oauth2:
    resource:
      id: API
      loadBalanced: true
      jwt:
        keyValue: -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3t2SxlBs8BFtUwE684jy
          lLx8M49TnqPibkZwsWWKPDjcLZDa2yTaM9/wjtdyF5drpHf+Y6oG9ZQZb8pgMXaY
          M2JvW9FlEh61Ju/2yA5wr/PP0qQChwoq9Y8jrZViY5ZLo56BzSjUU89tKfn34UQJ
          zlWuOmZGuIadW6q9BP9HC6MhZ3yxMJy02iHeaHWjwCF0A3L+1BTglPsSlhp6Afx/
          uHX9oqcoiuZlBr6s7rSFsKkWQWJ1Chx/bI7I5LGApVjb4WU4s9dV6+zt1Z4j+52b
          5uX77igsAzNBXehcFMKfRO/htGdnoLzz1j+aPwqzod1IzZr2j89+g+9ruaK6CaWG
          VQIDAQAB
          -----END PUBLIC KEY-----
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    metrics:
      enabled: true
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
## hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 120000
#hystrix.command.default.execution.timeout.enabled: false
#ribbon:
#  ConnectTimeout: 3000
#  ReadTimeout: 60000
#security:
#  oauth2:
#    resource:
#      id: API
#      loadBalanced: true
#      jwt:
#        keyValue: -----BEGIN PUBLIC KEY-----
#          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnY5zPuq27q6Q3yV+Dx3S
#          YnjBbahpysKwQCRAn+rZa+0RjHdfgPmgmwA84vlbDLPfBca1Kv8vkcpdjrPuqY1b
#          +2fQph7bIXBr5grGDL7fYy/fmg5GDLvbvfRdsqyb1vIAUZkk/lcxxFeRqk+SMjxd
#          QPcdAerzy1uivQ+mvUi7phewRW0dujsSLdgfgcSIkAZjI2j9UGjkK1rbbXcQp8v8
#          kZZSd/GTciQwssR8cznFtOuduhF2EUy7rlTZsn5X48yrOo3WaHsWI3/Oc7gaTqHe
#          kxNRWZVtBoOoca4k6YWYPwhQSARMPVLVcs7OsKwhtknYiA+CUcg1cwrksxxbvIMV
#          6wIDAQAB
#          -----END PUBLIC KEY-----
