server:
  port: 8888
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 1234
  cloud:
    config:
      server:
        git:
          uri: https://github.com/clustercamp/configurations.git
