kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: spinnaker-minio
  namespace: spinnaker
  labels:
    app: minio
    chart: minio-1.6.3
    heritage: Tiller
    release: spinnaker
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-data-spinnaker-redis-master-0
  namespace: spinnaker
  labels:
    app: redis
    chart: redis-3.8.0
    role: master
    release: spinnaker
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: halyard-home-spinnaker-spinnaker-halyard-0
  namespace: spinnaker
  labels:
    app: spinnaker-spinnaker
    component: halyard
    release: spinnaker
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
