apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-ship
  namespace: springcloud
  labels:
    category: micro-service
spec:
  replicas: 1
  selector:
    matchLabels:
      api: api-ship
  template:
    metadata:
      labels:
        api: api-ship
    spec:
      containers:
        - name: api
          image: cloudcamp/api-ship:1.0.1-arm64v8
          ports:
            - containerPort: 8080
          env:
            - name: spring.profiles.active
              valueFrom:
                configMapKeyRef:
                  name: clustercamp
                  key: active.profiles
            - name: spring.cloud.config.uri
              valueFrom:
                configMapKeyRef:
                  name: clustercamp
                  key: config.host
            - name: eureka.client.serviceUrl.defaultZone
              valueFrom:
                configMapKeyRef:
                  name: clustercamp
                  key: eureka.host
---
apiVersion: v1
kind: Service
metadata:
  name: api-ship
  namespace: springcloud
spec:
  selector:
    api: api-ship
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
