apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-ship
  namespace: springcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      api: api-ship
  template:
    metadata:
      labels:
        api: api-ship
    spec:
      containers:
        - name: api
          image: cloudcamp/api-ship:latest
          ports:
            - containerPort: 8080
          env:
            - name: spring.profiles.active
              valueFrom:
                configMapKeyRef:
                  name: springcloud
                  key: spring.profile
            - name: spring.cloud.config.uri
              valueFrom:
                configMapKeyRef:
                  name: springcloud
                  key: springcloud.config.uri
            - name: eureka.client.serviceUrl.defaultZone
              valueFrom:
                configMapKeyRef:
                  name: springcloud
                  key: springcloud.eureka.uri
---
apiVersion: v1
kind: Service
metadata:
  name: api-ship
  namespace: springcloud
spec:
  selector:
    api: api-ship
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
