language: node_js
node_js:
  - stable
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local-dir: "./build"
branches:
  only:
    - master
env:
  global:
    - secure: Rql14KI+W+Xe9IeJeM2k7a8UU+IeklYbFt4hZKYYOvJzw4IJeLh8sJ56OUqPi+CVKBql3qx/9UChiCov0A5n8tmQ4Q3X8LvUZVf1PPSr159vG1gNDi7gUblgMKiYT9t0vhOVNbcbjSThUUEJia9hOSax9E+RSmp/ZM2nHwbGorZIrV2QR8/19o8ri+AXQQOv/df4E0vW2B9eC0Axbshf23ZYYrznVdme4EPR2JNbKw5nh+j8F3J3H0t9gvBMWQL+f5VIRegS4z/xdwtmFnIJgEMFH1pVxk5B4B8MyvQhPRUgWxSJ7KyDwW4KM4pgVdIDkVlxLLFu/4+YxQmPyCT/RjkX2MpzZMhEcvXqCngSmlP/vdAYinmQZ9DvZTYkAjTECfHnKFRPcbL9TEkBtBYJT9GA6+CIMNcFdLxsfKD0endsgF1UGx05znChKBJ0eBAzHNA9XfwVyGuIoiXKXN4NlUwYDpOEisK+sdoObe1jNXaUaxadb/BA1sICr/nls/PeJhb7Yh+uuYN4vwQeQgA1ZiPnskmwWN7nfQ57rkTm2d8KPbYGnQow+xMBMHCx06sRyJdYEMLjp5N0tpQEk9wHDpSvFaR6le+5DU7P19kgdUdMmvnrFYmowtLlW4tfWUOCBaleG/GvtVvtaCQJkzcobL11pnpe+Gjzt2O8OYF6l2A=
