version: '3'
services:
  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_DATABASE=spring
      - MYSQL_USER=spring
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=1234567890
    volumes:
      - ./volumes/mysql:/var/lib/mysql
  config:
    container_name: config
    hostname: config
    image: cloudbuild/spring-cloud-config:latest
    ports:
      - "8080:8080"
    restart: always
    environment:
      WAIT_HOSTS: mysql:3306
