apiVersion: apps/v1
kind: Deployment
metadata:
  name: springcloud-hystrix
  namespace: springcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      springcloud: hystrix
  template:
    metadata:
      labels:
        springcloud: hystrix
    spec:
      containers:
        - name: app
          image: cloudcamp/springcloud-hystrix:latest
          resources:
            requests:
              memory: "700Mi"
            limits:
              memory: "800Mi"
          ports:
            - containerPort: 8080
          env:
            - name: spring.profiles.active
              valueFrom:
                configMapKeyRef:
                  name: springcloud
                  key: spring.profile
            - name: spring.cloud.config.uri
              valueFrom:
                configMapKeyRef:
                  name: springcloud
                  key: springcloud.config.uri
            - name: eureka.client.serviceUrl.defaultZone
              valueFrom:
                configMapKeyRef:
                  name: springcloud
                  key: springcloud.eureka.uri
---
apiVersion: v1
kind: Service
metadata:
  name: hystrix
  namespace: springcloud
spec:
  selector:
    springcloud: hystrix
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hystrix
  namespace: springcloud
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rule-type: "PathPrefixStrip"
    external-dns.alpha.kubernetes.io/target: home.cluster.camp
spec:
  rules:
    - host: hystrix.cluster.camp
      http:
        paths:
          - path: /
            backend:
              serviceName: hystrix
              servicePort: 8080

