apiVersion: apps/v1
kind: Deployment
metadata:
  name: security
  namespace: springcloud
  labels:
    framework: springcloud
    app: springcloud-security
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security
  template:
    metadata:
      labels:
        app: security
    spec:
      containers:
      - name: app
        image: hubtea/spring-cloud-security:latest
        ports:
        - containerPort: 8080
        env:
        - name: spring.profiles.active
          valueFrom:
            configMapKeyRef:
              name: base-config
              key: spring.profiles.active
        - name: eureka.client.serviceUrl.defaultZone
          valueFrom:
            configMapKeyRef:
              name: base-config
              key: spring.cloud.eureka.uri
        - name: spring.cloud.config.uri
          valueFrom:
            configMapKeyRef:
              name: base-config
              key: spring.cloud.config.uri
---
kind: Service
apiVersion: v1
metadata:
  name: security
spec:
  selector:
    app: security
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
