apiVersion: apps/v1
kind: Deployment
metadata:
  name: security
  namespace: springcloud
  labels:
    framework: springcloud
    app: springcloud-security
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security
  template:
    metadata:
      labels:
        app: security
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '80'
        prometheus.io/path: '/actuator/prometheus'
    spec:
      containers:
        - name: app
          image: dockercamp/springcloud-security:1.0.9-arm64v8
          ports:
            - containerPort: 80
          env:
            - name: spring.profiles.active
              valueFrom:
                configMapKeyRef:
                  name: clustercamp
                  key: active.profiles
            - name: spring.cloud.config.uri
              valueFrom:
                configMapKeyRef:
                  name: clustercamp
                  key: config.host
            - name: eureka.client.serviceUrl.defaultZone
              valueFrom:
                configMapKeyRef:
                  name: clustercamp
                  key: eureka.host
---
kind: Service
apiVersion: v1
metadata:
  name: security
  namespace: springcloud
spec:
  selector:
    app: security
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: security
  namespace: springcloud
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rule-type: "PathPrefixStrip"
    external-dns.alpha.kubernetes.io/target: home.proxy.camp
spec:
  rules:
    - host: security.cluster.camp
      http:
        paths:
          - path: /
            backend:
              serviceName: security
              servicePort: 80