apiVersion: apps/v1
kind: Deployment
metadata:
  name: security
  namespace: springcloud
  labels:
    framework: springcloud
    app: springcloud-security
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security
  template:
    metadata:
      labels:
        app: security
    spec:
      containers:
        - name: app
          image: cloudcamp/springcloud-security:1.0.2-arm64v8
          ports:
            - containerPort: 8080
          env:
            - name: spring.profiles.active
              valueFrom:
                configMapKeyRef:
                  name: clustercamp
                  key: active.profiles
            - name: spring.cloud.config.uri
              valueFrom:
                configMapKeyRef:
                  name: clustercamp
                  key: config.host
            - name: eureka.client.serviceUrl.defaultZone
              valueFrom:
                configMapKeyRef:
                  name: clustercamp
                  key: eureka.host
---
kind: Service
apiVersion: v1
metadata:
  name: security
  namespace: springcloud
spec:
  selector:
    app: security
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
