server:
  port: 8000
spring:
  application:
    name: FRONTEND
  rabbitmq:
    host: rabbitmq.springcloud.svc.cluster.local
    port: 5672
    username: springcloud
    password: springcloud
  sleuth:
    sampler:
      percentage: 0.2
sidecar:
  port: 5678
  health-uri: http://localhost:5678/health.json
zuul:
  routes:
    www:
      path: /frontend/**
      stripPrefix: true
      url: http://localhost:5678
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationDurationInSeconds: 5
  
