server:
  port: 8080
spring:
  application:
    name: HYSTRIX
turbine:
  appConfig: API-USER-SERVICE,API-CLIENT-SERVICE
  clusterNameExpression: "'default'"
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
