server:
  port: 80
spring:
  application:
    name: HYSTRIX
---
spring:
  profiles: dev
  boot:
    admin:
      client:
        url: http://eureka.springcloud.svc.cluster.local:8761/admin
        instance:
          preferIp: true
  rabbitmq:
    host: rabbitmq.springcloud.svc.cluster.local
    port: 5672
    username: springcloud
    password: springcloud
turbine:
  appConfig: API-USER,API-SHIP,API-SALE,API-GOOD
  clusterNameExpression: "'default'"
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
  instance:
    hostname: hystrix.cluster.camp
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    metrics:
      enabled: true
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'