apiVersion: apps/v1
kind: Deployment
metadata:
  name: sba
  namespace: springcloud
  labels:
    category: micro-service
spec:
  replicas: 1
  selector:
    matchLabels:
      api: sba
  template:
    metadata:
      labels:
        api: sba
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port:   '8080'
        prometheus.io/path: '/actuator/prometheus'
    spec:
      containers:
        - name: api
          image: dockercamp/springboot-admin:1.0.4-arm64v8
          ports:
            - containerPort: 8080
          env:
            - name: spring.profiles.active
              valueFrom:
                configMapKeyRef:
                  name: clustercamp
                  key: active.profiles
            - name: eureka.client.serviceUrl.defaultZone
              valueFrom:
                configMapKeyRef:
                  name: clustercamp
                  key: eureka.host
---
apiVersion: v1
kind: Service
metadata:
  name: sba
  namespace: springcloud
spec:
  selector:
    api: sba
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: 192.168.1.60
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sba
  namespace: springcloud
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rule-type: "PathPrefixStrip"
    external-dns.alpha.kubernetes.io/target: home.cluster.camp
spec:
  rules:
    - host: sba.cluster.camp
      http:
        paths:
          - path: /
            backend:
              serviceName: sba
              servicePort: 8080