server:
  port: 8080
spring:
  application:
    name: USER-SERVICE
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:/tmp/use
    username: sa
    password:
  jpa:
    showSql: true
    hibernate:
      ddlAuto: update
      formatSql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        formatSql: true
        id:
          newGeneratorMappings: true
  zipkin:
    baseUrl: http://zipkin.development.svc.cluster.local:9411
  sleuth:
    sampler:
      percentage: 0.2
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka.development.svc.cluster.local:8761/eureka/
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationDurationInSeconds: 5
