apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-good
  namespace: springcloud
  labels:
    category: micro-service
spec:
  replicas: 1
  selector:
    matchLabels:
      api: api-good
  template:
    metadata:
      labels:
        api: api-good
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port:   '8080'
        prometheus.io/path: '/actuator/prometheus'
    spec:
      containers:
        - name: api
          image: dockercamp/api-good:1.0.8-arm64v8
          ports:
            - containerPort: 8080
          env:
            - name: spring.profiles.active
              valueFrom:
                configMapKeyRef:
                  name: clustercamp
                  key: active.profiles
            - name: spring.cloud.config.uri
              valueFrom:
                configMapKeyRef:
                  name: clustercamp
                  key: config.host
            - name: eureka.client.serviceUrl.defaultZone
              valueFrom:
                configMapKeyRef:
                  name: clustercamp
                  key: eureka.host
---
apiVersion: v1
kind: Service
metadata:
  name: api-good
  namespace: springcloud
spec:
  selector:
    api: api-good
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
