server:
  port: 9010
spring:
  application:
    name: CLIENT-SERVICE
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:/tmp/client
    username: sa
    password:
  jpa:
    showSql: true
    hibernate:
      ddlAuto: update
      formatSql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        formatSql: true
        id:
          newGeneratorMappings: true
  zipkin:
    baseUrl: http://localhost:9411
  sleuth:
    sampler:
      percentage: 0.2
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationDurationInSeconds: 5
security:
  oauth2:
    resource:
      id: API
      loadBalanced: true
      jwt:
        keyValue: -----BEGIN PUBLIC KEY-----
                  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnY5zPuq27q6Q3yV+Dx3S
                  YnjBbahpysKwQCRAn+rZa+0RjHdfgPmgmwA84vlbDLPfBca1Kv8vkcpdjrPuqY1b
                  +2fQph7bIXBr5grGDL7fYy/fmg5GDLvbvfRdsqyb1vIAUZkk/lcxxFeRqk+SMjxd
                  QPcdAerzy1uivQ+mvUi7phewRW0dujsSLdgfgcSIkAZjI2j9UGjkK1rbbXcQp8v8
                  kZZSd/GTciQwssR8cznFtOuduhF2EUy7rlTZsn5X48yrOo3WaHsWI3/Oc7gaTqHe
                  kxNRWZVtBoOoca4k6YWYPwhQSARMPVLVcs7OsKwhtknYiA+CUcg1cwrksxxbvIMV
                  6wIDAQAB
                  -----END PUBLIC KEY-----
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
