server:
  port: 9030
spring:
  application:
    name: HYSTRIX
turbine:
  appConfig: USER-SERVICE,CLIENT-SERVICE,OAUTH-SERVICE
  clusterNameExpression: "'default'"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
