server:
  port: 9020
spring:
  application:
    name: OAUTH-SERVICE
  zipkin:
    baseUrl: http://localhost:9411
  sleuth:
    sampler:
      percentage: 0.2
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationDurationInSeconds: 5
