apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuul
  namespace: springcloud
  labels:
    framework: springcloud
    app: springcloud-zuul
spec:
  replicas: 1
  selector:
    matchLabels:
      springcloud: zuul
  template:
    metadata:
      labels:
        springcloud: zuul
    spec:
      containers:
      - name: app
        image: cloudcamp/springcloud-zuul:1.0.1-arm64v8
        ports:
          - containerPort: 8080
        env:
          - name: spring.profiles.active
            valueFrom:
              configMapKeyRef:
                name: clustercamp
                key: active.profiles
          - name: spring.cloud.config.uri
            valueFrom:
              configMapKeyRef:
                name: clustercamp
                key: config.host
          - name: eureka.client.serviceUrl.defaultZone
            valueFrom:
              configMapKeyRef:
                name: clustercamp
                key: eureka.host
---
apiVersion: v1
kind: Service
metadata:
  name: zuul
  namespace: springcloud
spec:
  selector:
    springcloud: zuul
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: zuul
  namespace: springcloud
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rule-type: "PathPrefixStrip"
    external-dns.alpha.kubernetes.io/target: home.cluster.camp
spec:
  rules:
    - host: zuul.cluster.camp
      http:
        paths:
          - path: /
            backend:
              serviceName: zuul
              servicePort: 8080
