server:
  port: 80
spring:
  application:
    name: API-GOOD
---
spring:
  profiles: dev
  boot:
    admin:
      client:
        url: http://eureka.springcloud.svc.cluster.local:8761/admin
        service-base-url: api-good.cluster.camp
        instance:
          preferIp: true
  data-initial: false
  datasource:
    url: jdbc:mysql://mysql.springcloud.svc.cluster.local:3306/spring?useUnicode=yes&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: spring
    password: spring1234
    initialization-mode: never
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
    generate-ddl: false
  rabbitmq:
    host: rabbitmq.springcloud.svc.cluster.local
    port: 5672
    username: springcloud
    password: springcloud
  zipkin:
    baseUrl: http://zipkin.springcloud.svc.cluster.local:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 0.2
security:
  oauth2:
    resource:
      jwt:
        keyValue: -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3t2SxlBs8BFtUwE684jy
          lLx8M49TnqPibkZwsWWKPDjcLZDa2yTaM9/wjtdyF5drpHf+Y6oG9ZQZb8pgMXaY
          M2JvW9FlEh61Ju/2yA5wr/PP0qQChwoq9Y8jrZViY5ZLo56BzSjUU89tKfn34UQJ
          zlWuOmZGuIadW6q9BP9HC6MhZ3yxMJy02iHeaHWjwCF0A3L+1BTglPsSlhp6Afx/
          uHX9oqcoiuZlBr6s7rSFsKkWQWJ1Chx/bI7I5LGApVjb4WU4s9dV6+zt1Z4j+52b
          5uX77igsAzNBXehcFMKfRO/htGdnoLzz1j+aPwqzod1IzZr2j89+g+9ruaK6CaWG
          VQIDAQAB
          -----END PUBLIC KEY-----
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka.springcloud.svc.cluster.local:8761/eureka/
  instance:
    hostname: api-good.cluster.camp
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: ALWAYS
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
