apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: springcloud
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - image: arm64v8/rabbitmq:3.7.14-alpine
          name: rabbitmq
          ports:
            - containerPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: springcloud
  labels:
    app: rabbitmq
spec:
  ports:
    - port: 5672
  selector:
    app: rabbitmq
