kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: spinnaker-minio
  namespace: spinnaker
  labels:
    app: minio
    chart: minio-1.6.3
    heritage: Tiller
    release: spinnaker
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi


  {
    "kind": "PersistentVolumeClaim",
    "apiVersion": "v1",
    "metadata": {
      "name": "jenkins-x-chartmuseum",
      "namespace": "jx",
      "selfLink": "/api/v1/namespaces/jx/persistentvolumeclaims/jenkins-x-chartmuseum",
      "uid": "69f842fb-794b-11e9-a1f1-c68b0e7139a9",
      "resourceVersion": "366090",
      "creationTimestamp": "2019-05-18T09:00:41Z",
      "labels": {
        "app": "jenkins-x-chartmuseum",
        "jenkins.io/chart-release": "jenkins-x",
        "jenkins.io/version": "2.0.276",
        "release": "jenkins-x"
      },
      "annotations": {
        "jenkins.io/chart": "jenkins-x-platform",
        "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"v1\",\"kind\":\"PersistentVolumeClaim\",\"metadata\":{\"annotations\":{\"jenkins.io/chart\":\"jenkins-x-platform\"},\"labels\":{\"app\":\"jenkins-x-chartmuseum\",\"jenkins.io/chart-release\":\"jenkins-x\",\"jenkins.io/version\":\"2.0.276\",\"release\":\"jenkins-x\"},\"name\":\"jenkins-x-chartmuseum\",\"namespace\":\"jx\"},\"spec\":{\"accessModes\":[\"ReadWriteOnce\"],\"resources\":{\"requests\":{\"storage\":\"8Gi\"}}}}\n"
      },
      "finalizers": [
        "kubernetes.io/pvc-protection"
      ]
    },
    "spec": {
      "accessModes": [
        "ReadWriteOnce"
      ],
      "resources": {
        "requests": {
          "storage": "8Gi"
        }
      },
      "volumeMode": "Filesystem"
    },
    "status": {
      "phase": "Pending"
    }
  }
