server:
  port: 8080
  use-forward-headers: true
spring:
  application:
    name: ADMIN
  boot:
    admin:
      ui:
        public-url: https://admin.cluster.camp
eureka:
  client:
    registryFetchIntervalSeconds: 5
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    metadata-map:
      startup: ${random.int}
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    metrics:
      enabled: true
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'